[webserver]
port = ":8686"
uri_prefix = "/tiles/"

[[providers]]
name = "pzf_gpkg"
type = "gpkg"
filepath = "/static/pzf.gpkg"

	[[providers.layers]]
	name = "pzf_data"
	srid = 4326
	sql = """
		SELECT
			fid, geom,
			NazObPZF, NZoPZF,
			AdmRozPZF, AdrAdmPZF,
			cast(PidDPZF as text) AS PidDPZF, PidNPZF,
			ZnPZF,
			cast(Updated as text) AS Updated,
			si.minx, si.miny, si.maxx, si.maxy
		FROM
			pzf lp
		JOIN
			rtree_pzf_geom si ON lp.fid = si.id
		WHERE
			!BBOX!
	"""

[[providers]]
name = "atu_oblast"
type = "gpkg"
filepath = "/static/oblast.gpkg"

	[[providers.layers]]
	name = "atu_oblast_data"
	srid = 4326
	sql = """
		SELECT
			fid, geom,
			ADMIN_1,
			si.minx, si.miny, si.maxx, si.maxy
		FROM
			oblast lp
		JOIN
			rtree_oblast_geom si ON lp.fid = si.id
		WHERE
			!BBOX!
	"""

[[providers]]
name = "atu_rayon"
type = "gpkg"
filepath = "/static/rayon.gpkg"

	[[providers.layers]]
	name = "atu_rayon_data"
	srid = 4326
	sql = """
		SELECT
			fid, geom,
			ADMIN_1, ADMIN_2,
			si.minx, si.miny, si.maxx, si.maxy
		FROM
			rayon lp
		JOIN
			rtree_rayon_geom si ON lp.fid = si.id
		WHERE
			!BBOX!
	"""

[[providers]]
name = "atu_terhromad"
type = "gpkg"
filepath = "/static/terhromad.gpkg"

	[[providers.layers]]
	name = "atu_terhromad_data"
	srid = 4326
	sql = """
		SELECT
			fid, geom,
			ADMIN_1, ADMIN_2, ADMIN_3, TYPE, KOATUU_old,
			si.minx, si.miny, si.maxx, si.maxy
		FROM
			terhromad lp
		JOIN
			rtree_terhromad_geom si ON lp.fid = si.id
		WHERE
			!BBOX!
	"""

[[providers]]
name = "index_gpkg"
type = "gpkg"
filepath = "/static/index_db.gpkg"

	[[providers.layers]]
	name = "index_data"
	srid = 4326
	sql = """
		SELECT
			fid, geom,
			koatuu, zona, kvart, add_date, layer,
			si.minx, si.miny, si.maxx, si.maxy
		FROM
			index_map lp
		JOIN
			rtree_index_map_geom si ON lp.fid = si.id
		WHERE
			!BBOX!
	"""


# register data providers
[[mvt_providers]]
name = "kadastr"
type = "postgis"
host = "${SQL_HOST}"
port = "${SQL_PORT}"
database = "postgres"
user = "${SQL_USER}"
password = "${SQL_PASS}"
srid = 3857

  [[mvt_providers.layers]]
  name = "river_line"
  geometry_fieldname = "geometry"
  geometry_type = "polygon"
  id_fieldname = "id"
  srid = 4326

  sql = """
  	SELECT
  		id,
  		CASE
  		 WHEN !ZOOM! < 6 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_8, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 8 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_10, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 10 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_12, 3857),ST_Transform(!BBOX!,3857))
         ELSE ST_AsMVTGeom(ST_Transform(geometry, 3857),ST_Transform(!BBOX!,3857)) END
        AS geometry,
  		properties->>'Власна назва (українською мовою)'  as name_ua,
  		(properties->>'Довжина, км')::int as length,
  		properties->>'Назва альтернативна' as alt_name,
		properties->>'Тип об’єкту гідрографії' as type,
		properties->>'Клас об’єкту гідрографії' as class,
		properties->>'Чия притока чи куди впадає' as destination,
		properties->>'Площа басейну' as basin_sq
	FROM public.geodata_georecord
	WHERE revision_id = (
		SELECT id
		FROM public.geodata_geojsonupload
		WHERE filename = 'river_line.geojson'
		ORDER BY id DESC
		LIMIT 1
	  ) AND
	  geometry && !BBOX!
  """


  [[mvt_providers.layers]]
  name = "nsdi_sm_merega"
  geometry_fieldname = "geometry"
  geometry_type = "polygon"
  id_fieldname = "id"
  srid = 4326

  sql = """
  	SELECT
  		id,
		CASE
  		 WHEN !ZOOM! < 6 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_8, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 8 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_10, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 10 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_12, 3857),ST_Transform(!BBOX!,3857))
         ELSE ST_AsMVTGeom(ST_Transform(geometry, 3857),ST_Transform(!BBOX!,3857)) END
        AS geometry,
		properties->>'site_code' as site_code,
		properties->>'Назва' as name,
		properties->>'Площа' as square,
		properties->>'Регіон' as region
	FROM public.geodata_georecord
	WHERE revision_id = (
		SELECT id
		FROM public.geodata_geojsonupload
		WHERE filename = 'nsdi_sm_merega.geojson'
		ORDER BY id DESC
		LIMIT 1
	  ) AND
	  geometry && !BBOX!
  """

  [[mvt_providers.layers]]
  name = "nsdi_river_basin"
  geometry_fieldname = "geometry"
  geometry_type = "polygon"
  id_fieldname = "id"
  srid = 4326

  sql = """
  	SELECT
  		id,
  		CASE
  		 WHEN !ZOOM! < 6 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_8, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 8 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_10, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 10 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_12, 3857),ST_Transform(!BBOX!,3857))
         ELSE ST_AsMVTGeom(ST_Transform(geometry, 3857),ST_Transform(!BBOX!,3857)) END
        AS geometry,
		properties->>'name_ua' as name,
		properties->>'Площа водозбору басейну, кв. км' as square
	FROM public.geodata_georecord
	WHERE revision_id = (
		SELECT id
		FROM public.geodata_geojsonupload
		WHERE filename = 'river_basin.geojson'
		ORDER BY id DESC
		LIMIT 1
	  ) AND
	  geometry && !BBOX!
  """


  [[mvt_providers.layers]]
  name = "nsdi_river_subbasin"
  geometry_fieldname = "geometry"
  geometry_type = "polygon"
  id_fieldname = "id"
  srid = 4326

  sql = """
  	SELECT
  		id,
  		CASE
  		 WHEN !ZOOM! < 6 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_8, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 8 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_10, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 10 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_12, 3857),ST_Transform(!BBOX!,3857))
         ELSE ST_AsMVTGeom(ST_Transform(geometry, 3857),ST_Transform(!BBOX!,3857)) END
        AS geometry,
		properties->>'name_ua' as name,
		properties->>'Код суббасейну' as code,
		properties->>'Площа водозбору суббасейну, кв. км' as square,
		properties->>'Назва басейну' as basin_name,
		properties->>'id' as id
	FROM public.geodata_georecord
	WHERE revision_id = (
		SELECT id
		FROM public.geodata_geojsonupload
		WHERE filename = 'river_subbasin.geojson'
		ORDER BY id DESC
		LIMIT 1
	  ) AND
	  geometry && !BBOX!
  """

  [[mvt_providers.layers]]
  name = "nsdi_manage_parcel"
  geometry_fieldname = "geometry"
  geometry_type = "polygon"
  id_fieldname = "id"
  srid = 4326

  sql = """
  	SELECT
  		id,
  		CASE
  		 WHEN !ZOOM! < 6 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_8, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 8 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_10, 3857),ST_Transform(!BBOX!,3857))
         WHEN !ZOOM! < 10 THEN ST_AsMVTGeom(ST_Transform(geometry_zoom_12, 3857),ST_Transform(!BBOX!,3857))
         ELSE ST_AsMVTGeom(ST_Transform(geometry, 3857),ST_Transform(!BBOX!,3857)) END
        AS geometry,
		properties->>'name_ua' as name,
		properties->>'Код' as code,
		properties->>'Площа, кв. км' as square,
		properties->>'Назва суббасейну' as subbasin_name
	FROM public.geodata_georecord
	WHERE revision_id = (
		SELECT id
		FROM public.geodata_geojsonupload
		WHERE filename = 'manage_parcel.geojson'
		ORDER BY id DESC
		LIMIT 1
	  ) AND
	  geometry && !BBOX!
  """

  [[mvt_providers.layers]]
  name = "land_polygons"
  geometry_fieldname = "geometry"
  geometry_type = "polygon"
  id_fieldname = "id"
  srid = 4326
  sql = """
    SELECT
      q.*,
      (SELECT address FROM cadinfo_address WHERE cadinfo_address.cadnum = q.cadnum) AS address
    FROM (
		SELECT
		  ST_AsMVTGeom(ST_AsBinary(geometry::geometry), !BBOX!) AS geometry,
		  ownership,
		  cadnum,
		  purpose,
		  category,
		  id
		FROM landuse
		WHERE
		  revision = (
			SELECT id
			FROM cadinfo_update
			WHERE status = 'success'
			ORDER BY id DESC
			LIMIT 1
		  ) AND
		  geometry && !BBOX!
    ) q

  """

  [[mvt_providers.layers]]
  name = "polygons"
  geometry_fieldname = "geometry"
  geometry_type = "polygon"
  id_fieldname = "id"
  srid = 3857
  sql = """
    SELECT ST_AsMVTGeom(ST_AsBinary(geometry), !BBOX!) AS geometry, 0 AS id
    FROM public.landuse_statistics WHERE geometry && !BBOX!
  """

  [[mvt_providers.layers]]
  name = "centroids"
  geometry_fieldname = "geometry"
  geometry_type = "point"
  id_fieldname = "id"
  sql = """
    SELECT ST_AsMVTGeom(ST_AsBinary(point), !BBOX!) AS geometry, to_char(parcels, '9 999 999') AS parcels, 0 AS id
    FROM public.landuse_statistics WHERE geometry && !BBOX!
  """

[[maps]]
name = "dzk_pzf"

  [[maps.layers]]
  provider_layer = "pzf_gpkg.pzf_data"
  min_zoom = 3
  max_zoom = 16

[[maps]]
name = "dzk_atu"

  [[maps.layers]]
  provider_layer = "atu_oblast.atu_oblast_data"
  min_zoom = 3
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "atu_rayon.atu_rayon_data"
  min_zoom = 8
  max_zoom = 16

  [[maps.layers]]
  provider_layer = "atu_terhromad.atu_terhromad_data"
  min_zoom = 10
  max_zoom = 16

[[maps]]
name = "dzk_index_map"

  [[maps.layers]]
  provider_layer = "index_gpkg.index_data"
  min_zoom = 11
  max_zoom = 16

[[maps]]
name = "dzk_water_map"

  [[maps.layers]]
  name="river_line"
  provider_layer = "mvt_kadastr.river_line"
  min_zoom = 3
  max_zoom = 14

  [[maps.layers]]
  name="nsdi_sm_merega"
  provider_layer = "mvt_kadastr.nsdi_sm_merega"
  dont_simplify = true
  min_zoom = 3
  max_zoom = 14

  [[maps.layers]]
  name="nsdi_river_basin"
  provider_layer = "mvt_kadastr.nsdi_river_basin"
  dont_simplify = true
  min_zoom = 3
  max_zoom = 14

  [[maps.layers]]
  name="nsdi_river_subbasin"
  provider_layer = "mvt_kadastr.nsdi_river_subbasin"
  dont_simplify = true
  min_zoom = 3
  max_zoom = 14

  [[maps.layers]]
  name="nsdi_manage_parcel"
  provider_layer = "mvt_kadastr.nsdi_manage_parcel"
  dont_simplify = true
  min_zoom = 3
  max_zoom = 14


[[maps]]
name = "kadastr"

  [[maps.layers]]
  provider_layer = "mvt_kadastr.polygons"
  min_zoom = 3
  max_zoom = 11

  [[maps.layers]]
  provider_layer = "mvt_kadastr.land_polygons"
  min_zoom = 11
  max_zoom = 16

  [[maps.layers]]
  provider_layer = "mvt_kadastr.centroids"
  min_zoom = 3
  max_zoom = 7

[cache]
  max_zoom = 14
  type = "file"
  basepath = "/cache"
