version: "3.5"
services:
  sphinx:
    image: macbre/sphinxsearch:3.4.1
    restart: unless-stopped
    ports:
    - "127.0.0.1:36307:36307" # bind to local interface only!
    volumes:
    - ${SPHINX_CACHE_DIR:-./data:/opt/sphinx/index/}
    - ./sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf
    - ./sphinx/sphinx_template.conf:/opt/sphinx/conf/sphinx_template.conf
    environment:
      - SQL_HOST
      - SQL_USER
      - SQL_PASS
      - SQL_DB
      - SQL_PORT

  tiles:
    build: tiles
    restart: unless-stopped
    ports:
      - 127.0.0.1:8686:8686
    environment:
      - SQL_HOST
      - SQL_USER
      - SQL_PASS
      - SQL_DB
      - SQL_PORT
    volumes:
      - ${TILES_CACHE_DIR:-/ssd/tegola_cache/:/cache/}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tiles.rule=PathPrefix(`/tiles/`)"
      - "traefik.http.routers.tiles.entrypoints=web,websecure"
      - "traefik.http.routers.tiles.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "containers.group=kadastr.live"

  wayback_tiles:
    build: wayback
    restart: unless-stopped
    environment:
      - SQL_HOST
      - SQL_USER
      - SQL_PASS
      - SQL_DB
      - SQL_PORT
    command:
      - --config
      - "/opt/tegola_config"
      - serve
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wayback_tiles.rule=PathPrefix(`/wayback_tiles/`)"
      - "traefik.http.routers.wayback_tiles.entrypoints=web,websecure"
      - "traefik.http.routers.wayback_tiles.middlewares=cors"
      - "traefik.http.services.wayback_tiles.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "containers.group=kadastr.live"

  raster:
    build: raster
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raster.rule=PathPrefix(`/tiles/raster`)"
      - "traefik.http.routers.raster.entrypoints=web,websecure"
      - "traefik.http.routers.raster.middlewares=cors,raster-stripprefix"
      - "traefik.http.middlewares.raster-stripprefix.stripprefix.prefixes=/tiles/raster"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "containers.group=kadastr.live"
    command: ["-p", "80", "-c", "/configs/config.json", "--public_url", "https://kadastr.live/tiles/raster"]

  nginx:
    build: vueapp
    restart: unless-stopped
    ports:
    - 127.0.0.1:8882:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.routers.nginx.priority=-1"
      - "traefik.http.routers.nginx.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "containers.group=kadastr.live"

  webserver:
    build: .
    restart: unless-stopped
    environment:
      - APP_MODULE=cadastr.wsgi:application
      - DEBUG
      - LOG_LEVEL=debug
      - SQL_HOST
      - SQL_USER
      - SQL_PASS
      - SQL_DB
      - SQL_PORT
    entrypoint: /app/start-reload.sh
    volumes:
      - .:/app
      - ./empty:/app/venv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/__debug__`) || PathPrefix(`/media`) || PathPrefix(`/static`) || PathPrefix(`/export`) || PathPrefix(`/search`) "
      - "traefik.http.routers.webserver.entrypoints=web,websecure"
      - "traefik.http.routers.webserver.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "containers.group=kadastr.live"

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`containers.group`,`kadastr.live`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entryPoints.web.forwardedHeaders.insecure"
    ports:
      - "127.0.0.1:11080:80"
      - "127.0.0.1:11443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/traefik/admin`) || PathPrefix(`/traefik/api`)|| HeadersRegexp(`Referer`, `.*/traefik/.*`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin-stripprefix"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.routers.traefik.priority=9999"
      - "traefik.http.middlewares.admin-stripprefix.stripPrefix.prefixes=/traefik/admin,/traefik/]"
      - "traefik.http.middlewares.admin-stripprefix.stripPrefix.forceSlash=true"
      - "containers.group=kadastr.live"
    depends_on:
      - nginx
      - webserver
      - tiles
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"